#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSMTenon.ReportGenerator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="birdtrack")]
	public partial class BirdTrackDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbto(bto instance);
    partial void Updatebto(bto instance);
    partial void Deletebto(bto instance);
    #endregion
		
		public BirdTrackDataContext() : 
				base(global::RSMTenon.ReportGenerator.Properties.Settings.Default.birdtrackConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BirdTrackDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BirdTrackDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BirdTrackDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BirdTrackDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bto> btos
		{
			get
			{
				return this.GetTable<bto>();
			}
		}
	}
	
	[Table(Name="dbo.bto")]
	public partial class bto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _bto_code;
		
		private string _species_name;
		
		private string _scientific_name;
		
		private bool _migrant_list;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbto_codeChanging(string value);
    partial void Onbto_codeChanged();
    partial void Onspecies_nameChanging(string value);
    partial void Onspecies_nameChanged();
    partial void Onscientific_nameChanging(string value);
    partial void Onscientific_nameChanged();
    partial void Onmigrant_listChanging(bool value);
    partial void Onmigrant_listChanged();
    #endregion
		
		public bto()
		{
			OnCreated();
		}
		
		[Column(Storage="_bto_code", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string bto_code
		{
			get
			{
				return this._bto_code;
			}
			set
			{
				if ((this._bto_code != value))
				{
					this.Onbto_codeChanging(value);
					this.SendPropertyChanging();
					this._bto_code = value;
					this.SendPropertyChanged("bto_code");
					this.Onbto_codeChanged();
				}
			}
		}
		
		[Column(Storage="_species_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string species_name
		{
			get
			{
				return this._species_name;
			}
			set
			{
				if ((this._species_name != value))
				{
					this.Onspecies_nameChanging(value);
					this.SendPropertyChanging();
					this._species_name = value;
					this.SendPropertyChanged("species_name");
					this.Onspecies_nameChanged();
				}
			}
		}
		
		[Column(Storage="_scientific_name", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string scientific_name
		{
			get
			{
				return this._scientific_name;
			}
			set
			{
				if ((this._scientific_name != value))
				{
					this.Onscientific_nameChanging(value);
					this.SendPropertyChanging();
					this._scientific_name = value;
					this.SendPropertyChanged("scientific_name");
					this.Onscientific_nameChanged();
				}
			}
		}
		
		[Column(Storage="_migrant_list", DbType="Bit NOT NULL")]
		public bool migrant_list
		{
			get
			{
				return this._migrant_list;
			}
			set
			{
				if ((this._migrant_list != value))
				{
					this.Onmigrant_listChanging(value);
					this.SendPropertyChanging();
					this._migrant_list = value;
					this.SendPropertyChanged("migrant_list");
					this.Onmigrant_listChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
